# Generated by Django 3.1.1 on 2020-10-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='background_image',
            field=models.URLField(default='https://source.unsplash.com/random/480x853'),
        ),
        migrations.AddField(
            model_name='org',
            name='button_label',
            field=models.CharField(default='Learn More', max_length=20),
        ),
        migrations.AlterField(
            model_name='org',
            name='subtitle_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
