# Generated by Django 3.1.1 on 2020-10-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20201009_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='organization_text',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
