# Generated by Django 3.1.1 on 2020-10-11 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_org_organization_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_detail_page_title', models.CharField(max_length=40)),
                ('org_detail_hero_image', models.URLField(default='https://source.unsplash.com/random/1080x1080')),
                ('org_detail_description', models.TextField(max_length=10000)),
                ('Org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.org')),
            ],
        ),
    ]
