# Generated by Django 3.1.1 on 2020-10-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_orgdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdetail',
            name='org_detail_description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu diam sed nunc suscipit pulvinar. Curabitur vel lobortis ipsum, ac tincidunt libero. Proin tincidunt suscipit rhoncus. Cras molestie turpis urna, nec bibendum risus egestas at. Curabitur diam massa, tincidunt in nunc id, volutpat euismod massa. Sed ornare et augue eu consequat. Curabitur quis sapien iaculis, sollicitudin nunc tempor, maximus mi. Etiam vulputate viverra neque nec dapibus. Ut vitae feugiat nunc, id feugiat eros. Sed et faucibus metus, et efficitur justo. Sed ac neque nunc. Vestibulum a tellus mi.', max_length=10000),
        ),
        migrations.AlterField(
            model_name='orgdetail',
            name='org_detail_page_title',
            field=models.CharField(default='About Us', max_length=40),
        ),
    ]
