# Generated by Django 3.1.1 on 2020-10-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_auto_20201011_0921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrgDetail',
            new_name='Detail',
        ),
    ]
