# Generated by Django 3.1.1 on 2020-10-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_auto_20201011_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='Org',
            new_name='org',
        ),
    ]
